version: '3.9'
services:
  npm:
    build: ./
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    
# Use this command to run a single service 

# docker-compose run <service-name-mentioned-in-docker-compose-file> <command>

# Sample 

# docker-compose run npm init