version: '3.9'
services:
  mongodb:
    container_name: mongodb
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=sushant
    #   - MONGO_INITDB_ROOT_PASSWORD=secret
    env_file:
      - $PWD/env/mongo.env
  backend:
    build: ./backend
    container_name: goals-backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - $PWD/env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    container_name: goals-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: